name: main workflow

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.4
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Java Home
        run: echo $JAVA_HOME
      
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze
        
      - name: Run Tests
        run: flutter test
